apiVersion :  v1
kind :  ConfigMap
metadata :
  name :  densifyconf 
  namespace : densify
data : 
  config.yaml : |
    forwarder:
        densify:
            url:
                scheme: https
                host: k11.densifydemo.com
                port: 30000
# Leave the credentials commented out as we will be populating these from environment variables.  These environment variables will, in turn, be populated by Kubernetes secrets
#                username: Admin
#                password: fdsrgfds
#                encrypted_password: <encrypted Densify password>
            endpoint: /api/v2/
    prometheus:
        url:
            scheme: http
            host: prometheus-kube-prometheus-prometheus.monitoring
            port: 9090
    collection:
    clusters:
        - name: minikube
