apiVersion: v1
kind: Pod
metadata:
  name: densify
  # Note: This line is not in the default example, it just forces everything into a namespace called "densify"
  namespace: densify
spec:
  containers:
  - image: densify/container-optimization-data-forwarder:4
    imagePullPolicy: Always
    name: data-forwarder
    volumeMounts:
    - mountPath: /config
      name: config
# BEGIN section that populates Densify credentials into ENV VARS from a secret named "densify-credentials"
    env:
    - name: DENSIFY_USER
      valueFrom:
        secretKeyRef:
          name: densify-credentials
          key: densify-username
    # Note: Change the below value to DENSIFY_EPASSWORD when using an EPASSWORD!
    - name: DENSIFY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: densify-credentials
          key: densify-password     
# END section that populates Densify credentials into ENV VARS from a secret named "densify-credentials" 
  volumes:
  - name: config
    configMap:
      name: densifyconf
      items:
        - key: config.yaml
          path: config.yaml
  restartPolicy: Never
